name: End-to-end Tests
on: [push]
jobs:
    Run-Tests:
        runs-on: ubuntu-latest
        container: cypress/browsers:node14.16.0-chrome89-ff86
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress Tests
              uses: cypress-io/github-action@v2
              with:
                  browser: chrome
